# Generated by Django 4.2.11 on 2026-07-13 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('resume_text', models.TextField(blank=True)),
                ('skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('experience_years', models.IntegerField(default=0)),
                ('resume_score', models.IntegerField(default=0)),
                ('resume_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('hr', 'HR Round'), ('tech', 'Technical Round'), ('behavioral', 'Behavioral Round'), ('completed', 'Completed')], default='hr', max_length=20)),
                ('hr_transcript', models.JSONField(default=list)),
                ('tech_transcript', models.JSONField(default=list)),
                ('behavioral_transcript', models.JSONField(default=list)),
                ('hr_score', models.FloatField(default=0.0)),
                ('tech_score', models.FloatField(default=0.0)),
                ('behavioral_score', models.FloatField(default=0.0)),
                ('hr_feedback', models.TextField(blank=True)),
                ('tech_feedback', models.TextField(blank=True)),
                ('behavioral_feedback', models.TextField(blank=True)),
                ('final_score', models.FloatField(default=0.0)),
                ('recommendation', models.CharField(blank=True, max_length=50)),
                ('suggested_title', models.CharField(blank=True, max_length=100)),
                ('training_plan', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='core.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='core.jobdescription')),
            ],
        ),
    ]
