# Generated by Django 4.2.11 on 2026-07-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='copy_paste_violations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='tab_focus_violations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='technical_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='technical_code_output',
            field=models.TextField(blank=True, default=''),
        ),
    ]
