# Generated by Django 4.2.11 on 2026-07-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_interviewsession_copy_paste_violations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='recruiter_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
