# Generated by Django 4.2.11 on 2026-07-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_interviewsession_recruiter_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='coding_challenge_desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='coding_challenge_starter_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='coding_challenge_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
